### ISSUE TITLE
Program ADSL

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#1]

**Comment by pstata** [comment]
can i also work this dataset

**Comment by thomas-neitmann** [comment]
@pstata Given the number of volunteers we have for this pilot submission it'd be great if you could keep your involvement to a single dataset for the time being. Thus, please assign yourself to either ADAE or ADSL. Thank you!

**Comment by pstata** [comment]
sure , * can work on ADSL for now*

**Comment by SHAESEN2** [comment]
Two discrepancies in AVGDD that I noticed is due to rounding difference between SAS an R. Will we implement an alternative rounding function or document this in ADRG?

**Comment by thomas-neitmann** [comment]
Are the values for `AVGDD` in the SAS dataset rounded?

**Comment by SHAESEN2** [comment]
> Are the values for `AVGDD` in the SAS dataset rounded?

Not as per define, but in the dataset itself they are.

**Comment by thomas-neitmann** [comment]
Strange. I don't think we should round values in the dataset.

**Comment by SHAESEN2** [comment]
#27

**Comment by SHAESEN2** [comment]
> Strange. I don't think we should round values in the dataset.

I agree but we would like to match the datasets so we should make an exception.
