### ISSUE TITLE
Update Readme for Package Repo

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#100]
Quick note on updating Readme on location of Pilot3 Helper package

**Comment by laxamanaj** [comment]
Hi, @kaz462 .  Can you work on this update?

**Comment by laxamanaj** [comment]
I believe, @SHAESEN2 has worked on this now and is merged in package repo : https://github.com/RConsortium/submissions-pilot3-utilities/pull/6
