### ISSUE TITLE
Convert Common Issues wiki to PDF

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#112]
https://github.com/RConsortium/submissions-pilot3-adam/wiki/Common-Issues

See  https://medium.com/@yakivmospan/did-you-ever-try-to-convert-github-wiki-in-pdf-c3078538bf12 or google other sources.

**Comment by SHAESEN2** [comment]
- Clone the repo:
https://github.com/RConsortium/submissions-pilot3-adam.wiki
- open md => choose preview as pdf
[Common-Issues.pdf](https://github.com/RConsortium/submissions-pilot3-adam/files/11720209/Common-Issues.pdf)
[QC-Findings.pdf](https://github.com/RConsortium/submissions-pilot3-adam/files/11720210/QC-Findings.pdf)

**Comment by robertdevine** [comment]
This a very cool, @SHAESEN2. Thank you.

@laxamanaj the approach used by @SHAESEN2 differs from what we discussed in our earlier meetings on Issue 59[1], 59[2] and has 'npm' dependency (github-wikito-converter) if Pilot3 wishes to programmatically generate the PDFs. [Node.js is not provided by default in posit cloud and the '[npm](https://cran.r-project.org/web/packages/V8/vignettes/npm.html)' package was removed from CRAN in 2022 but is available through the 'Archive' - a one liner using gwtc to convert the wiki to pdf.]. Love the ingenuity to present this alternative approach to convert GH Wiki to PDF! Thanks again.

[GH_Issue59_report-adam.pdf](https://github.com/RConsortium/submissions-pilot3-adam/files/11736366/GH_Issue59_report-adam.pdf)
