### ISSUE TITLE
Quarto website

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#113]
https://quarto.org/docs/publishing/github-pages.html

**Comment by robertdevine** [comment]
The Quarto '**_template.pptx_**' slides have been committed on the issue branch. [Interesting that the quarto template is style-free which leaves it to each team to stylize their content within the template and then point to that content using the '**reference_doc**' property in the quarto index file.  Should also note that quarto is available in Posit Cloud by default.].

**Comment by laxamanaj** [comment]
Let's revisit this at a later time.  Will close for now as our current website seems to meet our current needs at this time.
