### ISSUE TITLE
Exploring pkglite to pack pilot3 for ectd

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#126]

**Comment by robertdevine** [comment]
Thanks @laxamanaj, I'll explore as well while testing. Actually, while the team was in the early development stages of the pilot 3, I did use pkglite for packaging what the proposal identifies as the proprietary package.

**Comment by laxamanaj** [comment]
Per FDA and R consortium meeting. Pilot 3 has been given the 'ok' to submit without the use of {pkglite}.  Closing issue as no longer in scope.
