### ISSUE TITLE
Setup CI piplelines

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#13]
Would be great to have some CI pipelines to sensure good quality of our code. Im thinking of:

- R CMD check
- Spell check
- lintr
- styler

Looking at you @bms63 😉

**Comment by bms63** [comment]
I can bring over admiralci pipelines

**Comment by thomas-neitmann** [comment]
Perfect, thanks!

**Comment by laxamanaj** [comment]
Could be helpful to show how this works at our next weekly catch-up meeting as some may be new to this.

**Comment by thomas-neitmann** [comment]
Agreed!
