### ISSUE TITLE
Include Pilot 3 announcement to website

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#130]
This is the webpage to add : https://www.r-consortium.org/announcement/2023/09/11/first-publicly-available-r-based-submission-package-submitted-to-fda-pilot-3

**Comment by robertdevine** [comment]
@laxamanaj, the PR should be available on Friday (September 15, 2023). 

Since the [.qmd](https://quarto.org/docs/computations/r.html) file extension is not included on the in the FDA June 2023 [specification](https://www.fda.gov/media/85816/download) of approved file format types, seems advisable for Pilot3 to implement the requested webpage addition to the existing Pilot3 pkgdown website home page markdown file developed by @bms63.

**Comment by bms63** [comment]
@robertdevine the action to build the site is failing.  I'm not sure what got changed in the `renv.lock` file.  can look into it soon

**Comment by smartgxp** [comment]
Per recommend by @bms63, _pilot1 might not be the only issue - but also other packages needed to build the website.  I think[@Joel Laxamana](https://pharmaverse.slack.com team/U0493A50B5K) thinned out the lock file for the submission.   Perhaps searching back to the last time I published the site and grabbing that lock file is the best course of action._

In progress with this change and will issue a PR assigning @bms63 and @laxamanaj as _Reviewers_. Hopefully that will address the failed pkgdown check and successfully publish the _'Latest News_' section to the Pilot3 [website](https://rconsortium.github.io/submissions-pilot3-adam/main/index.html). 

Thanks.

**Comment by robertdevine** [comment]
Per recommend by @bms63  _pilot1 might not be the only issue - but also other packages needed to build the website. 
I think_ @laxamanaj  _thinned out the lock file for the submission. Perhaps searching back to the last time I published the site and grabbing that lock file is the best course of action._

In progress with this change and will issue a PR assigning @bms63  and @laxamanaj as Reviewers. Hopefully that will 
address the failed pkgdown check and successfully publish the 'Latest News' section to the Pilot3 website.

Thanks.

**Comment by robertdevine** [comment]
Thanks @laxamanaj and @bms63.

Confirmed @bms63, there is a **significant difference** in the lock file since the _website was successfully published_ and the _FDA submission_ events. Testing locally in my sandbox and will report here before issuing the PR.

**Comment by smartgxp** [comment]
Hi @laxamanaj  and @bms63, now running through the ADRG testing just to be certain nothing in the submission was affected by these lock updates. Testing Windows, Linux, and Mac, --- bare metal (company laptop) and cloud vm.  PR will get issued this week. So far, all looks good.

Thanks again.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/145378967/0fc86bd5-2178-4a6f-b8cd-14e2b19eb6b2)

**Comment by robertdevine** [comment]
Hi @laxamanaj and @bms63, testing the ADRG to confirm the submission programs and outputs are not affected by these updates to the lock. Testing Windows, Linux, and macOS on company laptop and cloud vm. Should be able to issue the PR this week. All looks good so far. 

Thanks again.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/ac369876-0a04-4153-930c-2e6dbf65e8cb)
