### ISSUE TITLE
Create Pilot3 .zip archives for  Rv4.2.1, and  Rv4.2.3 

### ISSUE THREAD

**Issue by robertdevine** [RConsortium/submissions-pilot3-adam#134]
Facilitate review for Pilot3 submission per feedback notes [here](https://github.com/RConsortium/submissions-wg/issues/95).
Additional archives can be generated based upon specific R versions.

**Comment by robertdevine** [comment]
The r-lib/zip compression [here](https://raw.githubusercontent.com/cwida/fsst/master/fsstcompression.pdf).

**Comment by robertdevine** [comment]
The .zip archives for Rv4.2.1 and Rv4.2.3 in preparation if FDA Reviewers request Pilot3 resubmission following the 1/5/ 2024 review.

**Comment by laxamanaj** [comment]
For now, I think we can close this as the lesson learned is to discuss with the FDA reviewers what R version they are using , then the sponsor adjusts to the R version aligned with the FDA. 
https://rconsortium.github.io/submissions-wg/minutes/2024-03-01/

Also look out for blog post on this subject.

**Comment by robertdevine** [comment]
Absolutely, @laxamanaj , the Pilot3 submission already provides the .zip archive for v4.2.3. 
Very similar ADRG pattern for any archived R version. Thx.
