### ISSUE TITLE
Update Website: feedback from FDA from March 2024 Meeting

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#137]
Update Website: feedback from FDA from December Meeting

**Comment by robertdevine** [comment]
@laxamanaj, @bms63 - since we already have the December 2023 RCRWG Meeting notes linked, issue updated for handling the March 2024 RCWG notes regarding FDA Feedback and action items. thx.

**Comment by bms63** [comment]
I must admit - I had no idea the WG kept such detailed minutes.  I really like linking the two together, but agree that we no longer need to re-summarize.

What do you think about linking additional notes up to say mid-Summer 2023?  This way we have links to pre-submission discussion and up to the submission in August?

I realize there a lot more notes going back into 2023...but sort of feel that they aren't really that relevant...
