### ISSUE TITLE
use envsetup instead of global variables

### ISSUE THREAD

**Issue by SHAESEN2** [RConsortium/submissions-pilot3-adam#15]
https://pharmaverse.github.io/envsetup/main/index.html

It would be good to promote opensource collaboration between pharma companies. I really like this package which attaches the paths to an environment. We can also use this system to automatically source functions (eg R/functions versus R/programs). I believe we do not need to stick to the strict package structure as long as we can package up everything nicely.

**Comment by thomas-neitmann** [comment]
I'm not sure this fits the requirements for a submission. Previous pilot submissions have put all custom developed functions into an R package and the used {pkglite} to transform the whole package into a single `.txt` file which could be included in the actual submission.
