### ISSUE TITLE
Correct Package and File names (description for more details).

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#150]
Need to update package name and align with the ADRG.  Similar with the submitted spec file.  To me, this is just a minor typo in the package name and the specs.  We just need to align the two filenames when we re-submit the ADRG.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/95468392/89a12458-ab2b-41a4-a118-ca44f8d42359)

**Comment by bms63** [comment]
Is our decision for the package to be called `pilot3utils`  ?  This makes the most sense to me.

**Comment by bms63** [comment]
Can confirm that the Package description is `pilot3utils`

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/db7dea3b-f9f0-47f1-ba62-0875a080f037)

**Comment by laxamanaj** [comment]
We need to do clean sweep of all of our documentation (adrg), pilot3utils repo, ADaM and output programs are all now referencing pilot3utils and not pilot3.

In the adrg.qmd of #156 , we need to do a search for the string 'pilot3', if referred to as a packge, then update to 'pilot3utils'.
In the *.r programs, we can do a grep call to search through all of the programs.

Otherwise, the adam-pilot-3.xlsx, the define.xml and the SAP, I don't believe will be referring to the pilot3 package.
