### ISSUE TITLE
Specify absolute (full) file path in ADRG

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#151]
Just need to update this section in the ADRG to note to reviewers to update the full file path instead of relative file path.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/95468392/9ed1e5db-907b-4709-ad23-2203dea9b620)

**Comment by SHAESEN2** [comment]
@laxamanaj  can you provide the docx file?
