### ISSUE TITLE
Link Summary of Pilots and Pilot 4 blog post

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#153]
We should do a little link for this blog post - nice summary of last three pilots and the future of pilot 4

https://pharmaverse.github.io/blog/posts/2024-02-01_containers_webassembly_submission/containers_and_webassembly_submissions.html

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/b3de6346-1e5f-45d9-a351-19098418f261)

**Comment by robertdevine** [comment]
@bms63 - will do - PR will get issued on Monday. thx.

**Comment by robertdevine** [comment]
@laxamanaj, @bms63 - added to **Latest News** section of the Pilot3 website. PR issued on Monday. thx.


![Image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/33d1fd60-aac5-4f05-ae1c-7316a9e400d1)
