### ISSUE TITLE
Remove stray newline on recent Pilot3 markdown update

### ISSUE THREAD

**Issue by robertdevine** [RConsortium/submissions-pilot3-adam#155]
@bms, @laxamanaj - looks like \n appears between bullet 2 and bullet 3 of the **Latest News** section of the README (yet the [website](https://rconsortium.github.io/submissions-pilot3-adam/main/index.html) renders properly). I'll update and re-issue removing the stray newline in the README for _consistency_. thx

**Comment by robertdevine** [comment]
@bms, @laxamanaj - actually the website renders correctly - just the markdown in the README renders the stray newline. We'll adjust the markdown so the README matches what renders correctly on the Pilot3 website. I'll issue PR on Monday.  thx.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/a5bffdd5-1560-44ba-bd7e-9e1bd91b4370)

**Comment by robertdevine** [comment]
@laxamanaj, @bms63 - this issue is completed. [Conflated with the ADRG PDF program updates earlier this week - bug fix is already live on Pilot3 website and markdown]. thx.

**Comment by bms63** [comment]
Thanks Robert!!  Feel free to close issues if you believe they have been completed.
