### ISSUE TITLE
Add to homepage: Statistical Software Clarifying Statement

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#159]
I was putting this in for my Pharmasug paper and thought it might be handy on Pilot 3 homepage

https://www.fda.gov/media/161196/download

**Comment by robertdevine** [comment]
@bms63 - Pilot3 website link to the Pharmasug paper submission should go under the '_Conferences_' menu or should it be under **Latest News** section? PR issued today. thx.

**Comment by bms63** [comment]
I was just thinking to have this Statement on the website with link.  Perhaps on the homepage.

I don't have a link to the pharmasug paper yet
