### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#167]
# Installation Instructions for installing a zip file packaged onto a Windows machine

## Step 1

Ensure that your "working directory" has the `renv-lock.txt` and `pilot3utils_0.0.2.zip` file

<img width="709" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/72df4023-5a56-449f-a506-c208e5aab6e5">

## Step 2

Change the `renv-lock.txt` to `renv.lock`

## Step 3

* install.pacakges("remotes")
* remotes::install_version("renv", version = "0.17.0")
* Confirming download and successful install

<img width="677" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/9d6666f1-ac96-4f88-ad62-3ba19ca3df05">

## Step 4

* Run `renv::init()` with selection 1

<img width="529" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/9d085cb2-1a5c-476e-9a7b-a1f1317fb9e7">

## Step 5

* Restart session 
* Issue pilot3 is still listed in lock file when using `renv::status` as well as unused package
* We might want to make a note on the unused packages

<img width="584" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/c819a6e0-664e-47fc-bf74-f32dfbfd845d">

## Step 6 

* Install the `pilot3utils` package from a zip file

### Select Package Pane and click install

<img width="525" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/a0972e27-2f2c-48ec-a607-9557f1a1dac9">

### Select Install From and choose Package Archive File

<img width="438" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/fbfe7188-1b43-4ab2-8147-4966480ea428">

### Click Browse and select zip file

<img width="1064" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/82482854-d714-4279-8c37-b4bfaae837b5">

### Click Install

<img width="405" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/a2d9ea39-99ae-4d9b-992e-9366382c2ae6">

### Successful install

<img width="741" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/f6c19331-8ff4-46d4-8417-fe902fde749d">

**Comment by bms63** [comment]
I was able to run the `adsl.R` program - just had to change pilot3 to pilot3utils in the library calls.  This is from the m5 module, which I don't think has been update from our dev repository

<img width="1407" alt="image" src="https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/800f99f9-9c4c-4653-b3c0-24db2011eca3">

Can confirm that I have access to the pilot3utils functions, but `adsl.R` doesn't use any of them

**Comment by robertdevine** [comment]
Thanks @bms63.

Steps 1 - 6 confirmed. Tests are successful - the only issue I ran into is a typo on _Step 3_ (above, modified to - >install.packages("remotes")). thx. again.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/5bf3237a-cab4-43e1-a6c4-e516e18fb724)

**Comment by bms63** [comment]
Do you some time to run the programs using `pilot3utils` ?  Just to make sure things work from the installed zip method??

**Comment by laxamanaj** [comment]
Thanks @bms63 and @robertdevine for your testing.  I also reran everything from our Pilot 3 dev repo and recopied over to the Pilot 3 adam-to-fda repo. Glad to see all of these steps worked.

**Comment by bms63** [comment]
that makes this way easier!!

**Comment by robertdevine** [comment]
@bms63, @laxamanaj  -confirmed - the Installation Instructions [Step 1 through Step6] work correctly if changes [1]-[5] are completed in order. The Pilot3 programs that need namespace and library updates ['pilot3utils'], those programs will need to be updated in two Pilot3 repositories. thx. [Pilot3 ADaM and Pilot3 FDA Submission repositories]

**Comment by laxamanaj** [comment]
> @bms63, @laxamanaj -confirmed - the Installation Instructions [Step 1 through Step6] work correctly if changes [[1]-[5]](https://github.com/RConsortium/submissions-pilot3-adam/issues/167#issuecomment-1998457428) are completed in order. The Pilot3 programs that need namespace and library updates ['pilot3utils'], those programs will need to be updated in two Pilot3 repositories. thx. [Pilot3 ADaM and Pilot3 FDA Submission repositories]

Agree, @robertdevine . In the pilot 3 development repo the {pilot3} package needs to be removed and reinstalled using the .zip and all library calls in the programs should be `library(pilot3utils)`. The Pilot 3 FDA submission repo will be updated with the copy script from the dev area.  New issue for this here : https://github.com/RConsortium/submissions-pilot3-adam/issues/168

**Comment by laxamanaj** [comment]
Hi, all.

Please see new updated steps in #156 with new images to help illustrate the steps.  I've run everything in my local computer following the steps using the folders from the eSUB repos.  Seems to be working well.

Notes : 
1. we need to go through all of the ADaM and output programs to ensure the new package being loaded is `{pilot3utils}` #168 
2. also call to metacore object `ADaM - Pilot 3.xlsx` should now be calling `adam-pilot-3.xlsx`. I don't mind if this is updated in #168 as well.

Otherwise all outputs came out on my end.  We can close this at the same time as #156 is merged.

**Comment by bms63** [comment]
Hi @laxamanaj - closing this issue as the ADRG has been updated with similar guidance and screenshots
