### ISSUE TITLE
Pkgdown will no longer build with current renv.lock

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#173]
@robertdevine @laxamanaj @SHAESEN2 

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/a12d3d51-20bc-4552-984e-2f01fb48ad00)

Hi all, 

The recent updates to the renv.lock file cause the pkgdown action to no longer build.  I see two ways forward:

1) We revert the changes to the renv.lock file for this repo and allow the action to work again.  We can make a note of this somewhere in the readme or in CI folder
2) We re-write the CI Action to no longer need the renv.lock file, but we will need to be careful on the package dependencies as some of the stats packages versions are not compatible with each other.

I think Choice 1 is the easiest way forward, but it makes the process less transparent. Choice 2 might be a bit more involved. Please advise.

**Comment by robertdevine** [comment]
@bms63, @laxamanaj , @SHAESEN2 - Choice 1 is the easiest way forwards to correct this in the short term. That said, the updated lock file that results in the pkgdown run failure for the website _does work_ successfully with the .zip Installation Instructions for regulatory testing (and will continue to do so if the lock file is reverted as in Choice 1). With Choice 2 one possible alternative to the lock file is to re-compose the **CI Action** using declarative dependency approach to navigate the stats package incompatibilities. thx.

**Comment by laxamanaj** [comment]
Hi, @robertdevine and @bms63 . I'm fine to go with the easiest approach here.  Option 1 works for me.

As for the renv.lock for the submission or re-submission if any, instead of snapshotting it in our development area with the website, instead we do the renv::snapshot in the final FDA eSUB repo , in that way the renv.lock will only snapshot the packages that are truly from the adam and tlg programs only.

**Comment by robertdevine** [comment]
Thanks @laxamanaj. I'll implement Option 1 next week and issue PR, @bms63. Thanks again.

**Comment by bms63** [comment]
i had a few minutes and fixed the build - we should have easier time wiht website updates going forward
