### ISSUE TITLE
Pilot3 Website - Latest News Update - RCWG Meeting Minutes April 2024 and May 2024 Editions

### ISSUE THREAD

**Issue by robertdevine** [RConsortium/submissions-pilot3-adam#176]
@laxamanaj , @bms63 , @kaz462 , @SHAESEN2 - updates to website to include RCWG April 2024 Meeting Minutes.
Should be all set for next Friday's Re-Submission. Thx.

**Comment by bms63** [comment]
Did this ever get addressed? https://github.com/RConsortium/submissions-pilot3-adam/issues/173

**Comment by robertdevine** [comment]
@bms63 - yes, I'll issue merged PR on Monday including #173 and #176. [RCWG](https://rconsortium.github.io/submissions-wg/minutes.html) has not yet posted April 2024 meeting minutes. thx.

**Comment by laxamanaj** [comment]
Hi, @robertdevine .  Main site April 2024 minutes now updated. 
https://rconsortium.github.io/submissions-wg/minutes/2024-04-05/Index.html

**Comment by robertdevine** [comment]
Thanks @laxamanaj - I'll issue PR on Friday including April and May 2024 RCWG Meeting Minutes. Thx.
