### ISSUE TITLE
refresh report-tlf.pdf

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#177]
Results should still be the same as here : https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/main/m1/us/report-tlf-pilot3.pdf 

Only timestamps should be updated to show that we refreshed for re-submission.

**Comment by robertdevine** [comment]
@laxamanaj , @bms63 - a {pilotwrappers} package dependency remains in tlf-demographic.Rmd.
![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/fccb269d-4555-4888-8d35-e26a44011eb9)

I'll remove that and refresh report-tlf.pdf with updated timestamps. Thx.

[This change does not affect the lock file in 'main'.]

**Comment by bms63** [comment]
Hey @robertdevine .  Any chance we can close this issue/PR before our meeting with the FDA on Monday?  We want to update the timestamp in m1 to be in line with the re-submission.  Thanks again for all your help!!

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/5dfef101-8e43-4e6e-907d-ece33ed0b58a)
![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/32931198-97d7-411d-8a4a-c948e16aaddc)

**Comment by robertdevine** [comment]
Hi @bms63 , absolutely - PR should be finalized later this afternoon. Thx.

**Comment by bms63** [comment]
![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/10111024/949c652a-3701-473a-8804-47c9e54dfcab)

**Comment by robertdevine** [comment]
Checking all the TLFs - looks good. Keeping pagination same as the August Submission. Thx.

![image](https://github.com/RConsortium/submissions-pilot3-adam/assets/8195239/631d8c90-8c55-4332-9704-449f44075bd3)

**Comment by robertdevine** [comment]
Should be all set here, @bms63 , @laxamanaj. For the August submission @laxamanaj ran locally to upload to the FDA repo. Let me know if you need me to do it. [Should be all set. Hats off to the Pilot3 Team.] Thanks. 

@kaz462, @SHAESEN2 - should be all set. Thx.
