### ISSUE TITLE
New links for site (R/Medicine and Online Talk)

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#187]
1. Pilot 3 Demo : R/Medicine 2024 :  
[https://rconsortium.github.io/RMedicine_2024/Program.html](https://urldefense.com/v3/__https:/rconsortium.github.io/RMedicine_2024/Program.html__;!!AoaiBx6H!wUjLnLOZgBqNIQOrK5QejKRcdDPAVdPulEpYvrOjuBZcimpakL2ttFI4rjKbqNx4UMgvgBjB9R6ED_qH4RXWUcc$) 

2. Pilot 3 Demo : useR! 2024 On-line talk : [https://www.youtube.com/watch?v=vPmNdHTVYm8&list=PL77T87Q0eoJhsC203plZ1H4p21AGrM9rl&index=12](https://urldefense.com/v3/__https:/www.youtube.com/watch?v=vPmNdHTVYm8&list=PL77T87Q0eoJhsC203plZ1H4p21AGrM9rl&index=12__;!!AoaiBx6H!wUjLnLOZgBqNIQOrK5QejKRcdDPAVdPulEpYvrOjuBZcimpakL2ttFI4rjKbqNx4UMgvgBjB9R6ED_qH8sTNzcA$)

**Comment by robertdevine** [comment]
Really great to see all the conference coverage with the RCWG pilots! Thanks.

**Comment by robertdevine** [comment]
@laxamanaj and @bms63 - Latest News Section of the Pilot3 Website updated with the R/Medicine and useR! 2024 links.
PR will get issued tomorrow. Thanks.

![image](https://github.com/user-attachments/assets/4e10bd37-e3e8-4ce4-b4ce-44b9fab722a5)

**Comment by robertdevine** [comment]
@bms63 - let's also add the link to the RCWG August 2024 Meeting Minutes in this PR. I'll take care of it - PR tomorrow. Thx.

**Comment by bms63** [comment]
Hey @robertdevine just checking if you completed this?

**Comment by robertdevine** [comment]
Commits to address both CheckURL CERT ERR responses get pushed today. The Pilot3 blog PR can then merge changes onto their sandbox branch and push. Thx.

**Comment by robertdevine** [comment]
Yep, @bms63, thanks again!
