### ISSUE TITLE
Pilot 3 completion blog post

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#188]
Ning Leng
Aug 2, 2024, 4:03 PM (4 days ago)
to Joseph, Eric, Jesse, Ben, Paul, Hye, Sam, Robert, me

Hi all,

Thanks for the discussion today! From today's meeting, we decided to start working on the pilot 3 completion blog so that it will be ready to publish once the FDA response letter is finalized.

I started a draft [here](https://docs.google.com/document/d/1lggFJinLHov8Vcfyk6iTHuyy-7cVpZuPDGe2SshGT28/edit) (also a convenience copy below in case you have issues with google doc). Any input is more than welcome!

Joe suggested we also include some educational components in the blog post. So I included a "learnings" section.

Thanks all
Ning

**Comment by lengning** [comment]
Two minor comments - 1) consider adding FDA staff names 2) move the sentence ‘ if you have any questions, we would love to …’ to an earlier section. Currently the sentence is under the pilot 1-3 learnings section which is not pilot 3 specific

**Comment by lengning** [comment]
Re the comment in learnings section regarding calling out more metrics on package quality checking - consider cite the  [riskmetrics package under R validation hub](https://www.pharmar.org/posts/news/updates-aug-2024/)

**Comment by laxamanaj** [comment]
> Re the comment in learnings section regarding calling out more metrics on package quality checking - consider cite the [riskmetrics package under R validation hub](https://www.pharmar.org/posts/news/updates-aug-2024/)

Thanks, for the insight @lengning . Good call out to the R validation Hub.  I updated the blog post with a paragraph on it.  Let me know what you think.

For convenience, here's an image capture of render : 
![image](https://github.com/user-attachments/assets/2e366a84-3d47-4d21-80cf-3d8de27546bc)

**Comment by robertdevine** [comment]
Thank you @lengning and @laxamanaj .Should also note here, the R Validation Hub recommendation was also cited on April 12, 2024. Excellent to include here. Thank you.

**Comment by laxamanaj** [comment]
> Thank you @lengning and @laxamanaj .Should also note here, the R Validation Hub recommendation was also cited on April 12, 2024. Excellent to include here. Thank you.

Hi, @robertdevine . Can you point me to where the R Validation Hub was cited on April 12, 2024?
