### ISSUE TITLE
Pilot3 Website - Latest News Update - RCWG Meeting Minutes September 2024 and October 2024 Editions

### ISSUE THREAD

**Issue by robertdevine** [RConsortium/submissions-pilot3-adam#191]
Update RCWG Meeting Minutes menu with link to the September 2024 edition.

**Comment by robertdevine** [comment]
@laxamanaj and @bms63 - PR will get issued with RCWG meeting links [Sept/Oct 2024]. Will assign you as Reviewers. 
Exciting RCWG General Meeting - wider submission pilot looks very cool. Thx.

**Comment by bms63** [comment]
Hey @robertdevine - I don't we need to capture these anymore.  I was only interested in highlighting minutes where Pilot 3 was discussed - but now there is no mention of us :(

**Comment by laxamanaj** [comment]
> Hey @robertdevine - I don't we need to capture these anymore. I was only interested in highlighting minutes where Pilot 3 was discussed - but now there is no mention of us :(
> 
> Hi @bms63 Today's Meeting Minutes [here](https://docs.google.com/document/d/1sLVicOpFXlT285-9pnH2ieY6fqtIlrjtkDh6shtvXM8/edit) - please feel free to message on Slack. We might form a Huddle group for the brainstorming about the next pilot. Thx. again.

We appreciate you, @robertdevine .  You still us a demo on how to create the final pdf including the 4 outputs in Pilot 3. :)
