### ISSUE TITLE
Program ADAE

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#2]

**Comment by laxamanaj** [comment]
Hi, @thomas-neitmann . I wanted to assign myself to this one, but it seems I'm not able to.

**Comment by laxamanaj** [comment]
I got it now!

**Comment by pstata** [comment]
I am also working on it too

**Comment by laxamanaj** [comment]
Hi, @pstata .  If you are already developing, we should be developing the ADAE program in a new branch.  I'll go ahead and create the branch here now, where then you'll then have to Pull this repo again, then switch over to the new branch `2_dev_adae_pstata`.  Then you can save your progress in this branch and push, then let me know.  I can then pull and try to rerun/update what you've developed so far.

**Comment by thomas-neitmann** [comment]
@pstata @laxamanaj Are yu making progress on this? If so, please open a pull request as @kaz462 and @SHAESEN2 did (even if not final) such that the current state of progress is transparanet to everyone in the team. Thanks!

**Comment by laxamanaj** [comment]
Hi, @thomas-neitmann .  I have not been making good progress on ADAE due to writing up the proposal and other project work that has been coming up lately.  In parallel, as I was working on the proposal, I was hoping @pstata was working on ADAE.  I'll follow up with him on slack.

**Comment by thomas-neitmann** [comment]
Thanks for the update @laxamanaj. I know you've been busy with other task and I'm very thankful you took them on! @pstata please let us know you're current state.

**Comment by laxamanaj** [comment]
Thank you so much again, @pstata  for getting adae.R started.  

Small update.  
- Updated to read in SDTM ae.xpt and ADaM ADSL.xpt (developed by pilot 3 team) from main. 
- added all ADSL keep variables. 
- Set adae$TRTA and TRTAN. 
- commented out max_date from AEENDTC derivation.

All ADSL variables added now and most of ADAE variables now matching, but still missing derivations for : 
```
Table: Variables not shared

version   variable    position  class     
--------  ---------  ---------  ----------
y         ASTDTF            16  character 
y         ASTDY             17  numeric   
y         AENDT             18  Date      
y         AENDY             19  numeric   
y         ADURN             20  numeric   
y         ADURU             21  character 
y         AOCCFL            48  character 
y         AOCCSFL           49  character 
```
Latest push to 2_dev_adae_laxamanaj.   Once these variables are in we will then PR to main as 'DRAFT'.  Will continue these next week.

@pstata , if you have time this week to add the rest of these variables, you'll need my updated adae.R script.  To get it please do : 
```
git checkout main
git pull
git checkout [your branch]
git merge --no-edit 2_dev_adae_laxamanaj
```

**Comment by pstata** [comment]
Thanks Laxman , I will take a look at them right today , Will update you

**Comment by pstata** [comment]
Hello Laxman , 

I think my program has these variables , some how I was able to see when I ran my program 
These are the list of variables in the ADAE dataset 

[1] "STUDYID"  "DOMAIN"   "USUBJID"  "AESEQ"    "AESPID"   "AETERM"   "AELLT"    "AELLTCD"  "AEDECOD"  "AEPTCD"   "AEHLT"    "AEHLTCD"   "AEHLGT"   "AEHLGTCD" "AEBODSYS" "AEBDSYCD" "AESOC"    "AESOCCD" 
[19] "AESEV"    "AESER"    "AEACN"    "AEREL"    "AEOUT"    "AESCAN"  
[25] "AESCONG"  "AESDISAB" "AESDTH"   "AESHOSP"  "AESLIFE"  "AESOD"   
[31] "AEDTC"    "AESTDTC"  "AEENDTC"  "AESTDY"   "AEENDY"   "TRTSDT"  
[37] "TRTEDT"   "DTHDT"    "EOSDT"    "ASTDTM"   "**ASTDTF**"   "ASTTMF"  
[43] "AENDTM"   "AENDTF"   "AENTMF"   "ASTDT"    "AENDT"    "TRTSDTM" 
[49] "astdt_m"  "aendt_m"  "TRTSDY"   **"ASTDY"    "AENDY"    "ADURN"**   
[55] "**ADURU**"    "TRTEMFL"  **"AOCCFL"   "AOCCSFL"**  "AOCCPFL"  "AOCC02FL"
[61] "AOCC03FL" "AOCC04FL" "CQ01NAM"  "AOCC01FL"


I am sending you the program that I am using , just see if you have that program in the Git , I am sending as attachment here , not sure if you can download it or not . I can send you has email or on Slack once I reach home 
 
[adae.txt](https://github.com/RConsortium/submissions-pilot3-adam/files/10472653/adae.txt)

**Comment by laxamanaj** [comment]
Thanks for the update, @pstata !  I will check and update by this week before our Friday meeting and do a PR.
