### ISSUE TITLE
renv.lock

### ISSUE THREAD

**Issue by SHAESEN2** [RConsortium/submissions-pilot3-adam#24]
Would it be a possibility to include renv.lock into submission to help reviewers to reconstruct our environment?

**Comment by thomas-neitmann** [comment]
I am all for that but I'm not sure how we could do that. I think the eCTD is rather restrictive on what you can submit. But let's investigate. Would also be good to catch up with the other pilot teams to ask why they did not follow this approach.

**Comment by laxamanaj** [comment]
Looks like we will just follow the Pilot 1 approach and create this `r0pkgs.txt` 

https://r4csr.org/submission-package.html#prepare-r-packages-for-submission

![image](https://user-images.githubusercontent.com/95468392/225967148-6d9377c9-054e-45c5-a5d6-0ace4781217a.png)
