### ISSUE TITLE
update ADRG

### ISSUE THREAD

**Issue by wangben718** [RConsortium/submissions-pilot3-adam#28]

**Comment by thomas-neitmann** [comment]
Please provide a bit on context on the planned updates, thanks!

**Comment by wangben718** [comment]
> Please provide a bit on context on the planned updates, thanks!

I saw there is a `/vignettes/adrg-prepare.rmd` file and it seems like we need to update and re-genereate the output.

**Comment by laxamanaj** [comment]
One thing to note, we have a pilot 3 proposal, which was based on ADRG from pilot 2.  So with this proposal, we can use this info to create ADRG for pilot 3. see #17

**Comment by laxamanaj** [comment]
@wangben718 as mentioned above.  In #17, please take a copy of the Pilot 3 proposal that is attached there.  Then you may open up the current `/vignettes/adrg-prepare.rmd` and update it (copy and paste) using info from this proposal for our Pilot 3 ADRG.  Let me know if this makes sense.  Thanks.

**Comment by laxamanaj** [comment]
Completed.  See here : https://github.com/RConsortium/submissions-pilot3-adam-to-fda/blob/main/m5/datasets/rconsortiumpilot3/analysis/adam/datasets/adrg.pdf
