### ISSUE TITLE
Graph/Figure - KM plot for Time to First Dermatologic Event : Safety Population

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#32]
Once #2 and #5 are complete. Reproduce this graph/figure. See link for Pilot 1 TLG report in #6 .

**Comment by SHAESEN2** [comment]
Could we use ggsurvfit package instead? It is a spin-off from visR focussed on only graphs

**Comment by thomas-neitmann** [comment]
we indicated that we would re-submit the programs from pilot 1 only with necessary updates due to changes in the packages used so I feel this is out of scope.

**Comment by robertdevine** [comment]
Preparing this issue sandbox for the CDISC {admiral} hackathon upcoming on January 26, 2023. Hopefully many team members can attend. Thanks.
