### ISSUE TITLE
ADAE TRTEMFL comparison issue 

### ISSUE THREAD

**Issue by pstata** [RConsortium/submissions-pilot3-adam#38]
Hello Thomas , 

This is how I am deriving TRTEMFL when trying to compare with SAS dataset I am not sure where the differences are , can you take a look what is that I am missing here 

library(haven)
library(curl)

adsl  <- read_xpt("https://github.com/RConsortium/submissions-pilot3-adam/blob/main/adam/adsl.xpt?raw=true")
adae_or <- read_xpt("https://github.com/RConsortium/submissions-pilot3-adam/blob/main/adam/adae.xpt?raw=true")

ae_EM<- adae_or %>% 
  select (USUBJID ,AESEQ ,  ASTDT , ASTDTC, TRTSDT , TRTEMFL ) %>% 
  arrange(USUBJID,AESEQ , ASTDT , TRTSDT)
# Compare with referance program
ae_EM <- convert_blanks_to_na(ae_EM)

# mutate(
#   TRTEMFL = ifelse(ASTDT >= TRTSDT & ASTDT <= TRTEDT + days(30), "Y", NA_character_)
#   
ae <- convert_blanks_to_na(ae)
ex <- convert_blanks_to_na(ex_single)

# Derivations ----

# Get list of ADSL vars required for derivations
adsl_vars <- vars(TRTSDT, TRTEDT, DTHDT, EOSDT)

adae <- ae %>%
  # join adsl to ae
  derive_vars_merged(
    dataset_add = adsl,
    new_vars = adsl_vars,
    by = vars(STUDYID, USUBJID)
  ) %>%
  ## Derive analysis start time ----
derive_vars_dtm(
  dtc = AESTDTC,
  new_vars_prefix = "AST",
  highest_imputation = "M",
  min_dates = vars(TRTSDT)
)

ae_trtemfl <- adae %>% 
  select (USUBJID,AESEQ , ASTDT , TRTSDT  , TRTEMFL    )  %>% 
  arrange(USUBJID,AESEQ , ASTDT , TRTSDT)

# DERIVE_VAR_TRTE

ae_emfl <- adae %>% 
  select (USUBJID,AESEQ , ASTDT , TRTSDT , AENDT ) 

ae_emfl <- 
derive_var_trtemfl(
  ae_emfl ,
  new_var = TRTEMFL,
  start_date = ASTDT ,
  end_date = AENDT ,
  trt_start_date = TRTSDT ,
  trt_end_date = NULL,
  end_window = NULL,
  ignore_time_for_trt_end = TRUE,
  initial_intensity = NULL,
  intensity = NULL
)

ae_EM <-  tibble(convert_blanks_to_na(ae_EM))

 ae_EM<- ae_EM %>% 
  select (USUBJID ,  AESEQ , TRTEMFL )%>%  
  mutate ( AESEQ =  as.numeric(AESEQ) ) %>% 
  arrange(USUBJID,AESEQ  )
 
 ae_emfl <- tibble(convert_blanks_to_na(ae_emfl ))
 
ae_emfl <- ae_emfl %>% 
  select (USUBJID , AESEQ , TRTEMFL)%>% 
  arrange(USUBJID,AESEQ )

summary(comparedf(ae_EM , ae_emfl , by = "USUBJID"   ) )

**Comment by kaz462** [comment]
hi @pstata the differences are caused by below two reasons:
1. ASTDT highest imputation should be Day `derive_vars_dtm(..., highest_imputation = "D")` as specified in define;
2. TEAE is not flagged when ASTDT is missing based on the define (not taking the conservative approach).

I tried the below code to derive TEAE, and got the same results as CDISC pilot ADAE.TRTEMFL, hope it helps:
```r

ae <- convert_blanks_to_na(read_xpt(file.path("sdtm", "ae.xpt"))) 
adsl <- convert_blanks_to_na(read_xpt(file.path("adam", "adsl.xpt")))
  
ae_teae <- ae %>% 
  derive_vars_merged(
    dataset_add = adsl,
    new_vars = vars(TRTSDT, TRTEDT),
    by = vars(STUDYID, USUBJID)
  ) %>%
  # ASTDTM
  derive_vars_dtm(
    dtc = AESTDTC,
    new_vars_prefix = "AST",
    highest_imputation = "D"
  ) %>%
  # AENDTM
  derive_vars_dtm(
    dtc = AEENDTC,
    new_vars_prefix = "AEN",
    highest_imputation = "h"
  ) %>%
  derive_vars_dtm_to_dt(vars(ASTDTM, AENDTM)) %>%
  ## TRTEMFL
  restrict_derivation(
    derivation = derive_var_trtemfl,
    args = params(
      start_date = ASTDT,
      end_date = AENDT,
      trt_start_date = TRTSDT
    ),
    filter = !is.na(ASTDT)
  ) %>%
  select(USUBJID, AESEQ, ASTDT, AENDT, TRTEMFL)

adae <- convert_blanks_to_na(read_xpt(file.path("adam", "adae.xpt")))

library(diffdf)
diffdf(ae_teae, 
       adae %>% select(USUBJID, AESEQ, ASTDT, AENDT, TRTEMFL), 
       keys = c("USUBJID", "AESEQ"))
```

**Comment by laxamanaj** [comment]
Thank you for this, @kaz462 . I was able to update adae.R with your apporach.  
cc @pstata .
![image](https://user-images.githubusercontent.com/95468392/218547096-2ec373bd-a1bd-4e04-9c36-33ced0be6de3.png)
