### ISSUE TITLE
Program ADADAS

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#4]

**Comment by kaz462** [comment]
Hi, @thomas-neitmann. I'm not able to assign myself to an issue.
For ADAS in define.xml, the last column doesn't seem right, it's mostly populated as "LB.VISITNUM".

**Comment by thomas-neitmann** [comment]
I hadn't added you as a contributor to this repo, yet, so you couldn't assign yourself @kaz462. That's fixed now. Thanks for taking this on!
