### ISSUE TITLE
Update website url and gh-pages folder for pkgdown site

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#42]
Hi all,

Could I be given admin access so I can set up the packagedown site infrastructure and update the url in the About?

![image](https://user-images.githubusercontent.com/10111024/210883131-93fb4606-9a9c-4578-b96a-2459397fcef4.png)

**Comment by laxamanaj** [comment]
Hi, @bms63 .  Now that you have admin, can this be closed?
