### ISSUE TITLE
Snapshot on Readme is out of date

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#43]
I think we are using 2022-12-14

![image](https://user-images.githubusercontent.com/10111024/211064231-3adbc4f4-897d-4e7d-8ca2-cdecea65ed20.png)

**Comment by bms63** [comment]
Also, another point for OS - we test on Windows and Mac in https://github.com/RConsortium/submissions-pilot3-adam/pull/36

**Comment by robertdevine** [comment]
@bms63 Shouldn't be necessary as the ADRG appendices already include OS-specific instructions for review and comment. Thank you.

**Comment by bms63** [comment]
@thomas-neitmann  the MRAN issue shows up here as well.  Shall we update to R Package Manager for our snapshot.  Might want to update the lock file as well??

**Comment by thomas-neitmann** [comment]
@bms63 Yes and yes 🙂

**Comment by laxamanaj** [comment]
Hi, @bms63 .  Can you help update the README?
