### ISSUE TITLE
Program ADTTE

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#5]

**Comment by robertdevine** [comment]
CDISC ADaM Basic Data Structure for Time-to-Event Analysis Version 1.0. 
[adam_tte_final_v1.pdf](https://github.com/RConsortium/submissions-pilot3-adam/files/9992379/adam_tte_final_v1.pdf)

https://www.cdisc.org/standards/foundational/adam/adam-basic-data-structure-bds-time-event-tte-analyses-v1-0

**Comment by thomas-neitmann** [comment]
[Creating a BDS Time-to-Event ADaM](https://pharmaverse.github.io/admiral/articles/bds_tte.html) vignette from {admiral}

**Comment by SHAESEN2** [comment]
I started branch adtte. Everyone can contribute on this one.

**Comment by robertdevine** [comment]
@wangben718 does that work for you? Please let us know your thoughts. Thank you.

**Comment by robertdevine** [comment]
Example adtte provided cdisc.
https://www.cdisc.org/kb/examples/pancreatic-cancer-adtte-survival-and-duration-follow-103759150

**Comment by SHAESEN2** [comment]
The program is more or less finalized and QC'd against the original ADTTE. There is one difference and I'm not sure where it comes from:

Subject 01-710-1083 I find ADT =2013-08-02 vs 2013-08-03. Perhaps someone can have a look why CDISC finds 2013-08-03?

@thomas-neitmann Did we already agree in which folder to output the datasets and in which format?

**Comment by SHAESEN2** [comment]
> The program is more or less finalized and QC'd against the original ADTTE. There is one difference and I'm not sure where it comes from:
> 
> Subject 01-710-1083 I find ADT =2013-08-02 vs 2013-08-03. Perhaps someone can have a look why CDISC finds 2013-08-03?

Subject discontinues on 2013-08-02 and dies on 2013-08-03. In the original ADaM they use the death date instead of the discontinuation date. I adjusted the code to use the death date instead of the discontinuation date to be able to match. However, this is not documented in the original specs as far as I can see. After the update the dataset content matches 100%.

**Comment by thomas-neitmann** [comment]
Please open a pull request @SHAESEN2.

We should save the dataset as an `.xpt` file making use of {xportr}. I'm open to suggestions on where to save.

**Comment by robertdevine** [comment]
Hi @SHAESEN2, at today's Pilot3 meeting the team discussed options to proceed with adtte data set. @thomas-neitmann recommended to start with a new branch. The recommendation seemed reasonable to the discussion. The adtte_bdstte branch was created for this purpose. Thank you.

**Comment by SHAESEN2** [comment]
It is more efficient to pull in the existing branch and then create your branch to make modifications. Alternative you could create a sub-branch of the existing one. I don't see the purpose of starting a new branch. Let me know if you need help with this.

**Comment by robertdevine** [comment]
Issue #5: ADTTE .R files [Test sandbox Ubuntu + Windows VM]
**Sprint #1**: 12-5 to 12-9
Read in Data
Derive Parameters (CNSR, ADT, STARTDT)
Derive Analysis Value (AVAL)
Sprint #2: 12-12 to 12-16
Derive Analysis Sequence Number
Add ADSL Variables

Deliverable: Draft PR on whichever branch on 12-16-2022


@thomas-neitmann please let us know if there is a branch preference. Thanks.
