### ISSUE TITLE
ADTTE define: Add value level (AVAL) derivation for the completion of define.xml 

### ISSUE THREAD

**Issue by kaz462** [RConsortium/submissions-pilot3-adam#51]
This issue is for the final completion of define.xml
#10 is a big topic, I'm trying to split it into small pieces.
For the `ValueLevel` sheet, only ADTTE and ADADAS are needed as these two datasets have derived parameters.

**Comment by robertdevine** [comment]
Thank you, @kaz462. AVAL derived as elapsed time (in days) to event of interest or CNSR>=0. [ADINTDT dataset for traceability support or input to ADTTE is out of scope here. Please comment if otherwise.]

**Comment by kaz462** [comment]
@robertdevine  I just realized there is only one derived parameter in `ADTTE`, and there is already derivation in `Variable` level, so no need to populate `ValueLevel` for `ADTTE`. thanks for the quick responses and sorry for the confusion!
