### ISSUE TITLE
Create workflow of m5 submission process

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#53]
https://github.com/RConsortium/submissions-pilot1-to-fda

**Comment by bms63** [comment]
I think it would be good to create a high-level overview of how the pilot1 and pilot2 groups did their submission.  This could be in the form of a vignette that we host on our packagedown site or an internal Rmarkdown file that we can reference for anyone who needs help understanding the process - I need that help! :) 

@thomas-neitmann @laxamanaj @SHAESEN2 @kaz462

**Comment by bms63** [comment]
See https://github.com/RConsortium/submissions-pilot1-to-fda

**Comment by laxamanaj** [comment]
Actually we have this adam-to-fda repo forked for Pilot 3 as well, so we can begin updating this area : https://github.com/RConsortium/submissions-pilot3-adam-to-fda

**Comment by laxamanaj** [comment]
For some initial thoughts, this is what I see we can begin populating in the adam-to-fda repo
```
m1
└── us
    ├── cover-letter.pdf  # Submission cover letter
    ├── proposal slides.pdf  #get from link here : https://github.com/RConsortium/submissions-wg/blob/main/_Documents/R_Submission_Pilot_3_ADaM_Proposal.pdf 
    ├── R_Submission_Pilot_3_ADaM_FDA_Execution_Proposal_02Dec2022.pdf  # FDA Execution proposal : https://github.com/RConsortium/submissions-pilot3-adam/blob/main/vignettes/fda/R_Submission_Pilot_3_ADaM_FDA_Execution_Proposal_02Dec2022.pdf
    └── report-tlf.pdf    # Submission TLFs to show that we were able to regenerate the TLF that pilot 1 has submitted with potential slight differences due data differences.
```

```
m5
└── datasets
    └── rconsortiumpilot3
        └── analysis
            └── adam
                ├── datasets              # ADaM datasets in XPT format
                │   ├── adadas.xpt
                │   ├── adae.xpt
                │   ├── adlbc.xpt
                │   ├── adrg.pdf          # Analysis Data Reviewer's Guide
                │   ├── adsl.xpt
                │   ├── adtte.xpt
                │   ├── define.xml        # ADaM data define file
                │   └── define2-0-0.xsl
                └── programs
                    ├── r0pkg.txt         # Proprietary R package in txt format
                    ├── adsl.R # ADaM R code 
                    ├── adae.R # ADaM R code 
                    ├── adlbc.R # ADaM R code 
                    ├── adtte.R # ADaM R code 
                    ├── adadas.R # ADaM R code 
                    ├── tlf-demographic.r # analysis R code for TLFs. 
                    ├── tlf-efficacy.r
                    ├── tlf-kmplot.r
                    └── tlf-primary.r
```

**Comment by bms63** [comment]
Hey @laxamanaj I started making issues in the submission repo.  We can link them onto the same board so we can keep track of progress on the two repos

**Comment by laxamanaj** [comment]
@DeclanHodges , created a nice copy script here to prepare the m5 in the pilot3-adam-to-fda repo : https://github.com/RConsortium/submissions-pilot3-adam-to-fda/pull/9 

Closing this issue to continue further updates in issue 9 linked in this comment.
