### ISSUE TITLE
Common Issues facing Datasets

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#57]

**Comment by bms63** [comment]
Collate common issues noticed in dataset compares, package issues, etc.

**Comment by kaz462** [comment]
# 1. Package issue tracking 
## 1.1 Package issues
* `haven::read_xpt()`
Some attributes are dropped after using `haven::write_xpt()` `haven::read_xpt()`, e.g., type, length. 
to do:  further check

* `xportr::xportr_length()` 
`NA_character_` is considered as length 2 - [issue resolved on Dec 14, 2022](https://github.com/tidyverse/haven/issues/699) 
to do: to be incorporated in pilot3

## 1.2 Potential improvement
* `metatools::build_from_derived()`
https://github.com/pharmaverse/metatools/issues/46
Not urgent feature but nice to have - especially when `define.xml` is not in good quality

# 2. Knowledge sharing
Summary of similarities and differences between packages, to help user identify the best tool that suits the need. 
Maybe this could go to [Bayer SAS2R catalog](https://bayer-group.github.io/sas2r/) in the future, 

### `metatools` vs `xportr` 
* `metatools::set_variable_labels()` vs `xportr::xportr_label()` 

### `xportr` vs `haven` 
* `xportr::xportr_write()` vs `haven::write_xpt()`  

### `diffdf` vs `arsenal`
* `diffdf::diffdf()` vs `arsenal::comparedf()`

**Comment by laxamanaj** [comment]
Lets add this to wiki : https://github.com/RConsortium/submissions-pilot3-adam/wiki 

in a new page.

**Comment by kaz462** [comment]
> * `haven::read_xpt()`
>   Some attributes are dropped after using `haven::write_xpt()` `haven::read_xpt()`, e.g., type, length.
>   to do:  further check

just found an issue has been posted for `haven::read_sas/xpt`
https://github.com/tidyverse/haven/issues/718

**Comment by laxamanaj** [comment]
Thank you, @kaz462 for creating this issue and tracking common issues.  I was able to add this as new page to our wiki, which is here : https://github.com/RConsortium/submissions-pilot3-adam/wiki/Common-Issues 

For now I will go ahead and close this issue.  If any further `Common Issues` come up, we can add them directly to this new Wiki page.
