### ISSUE TITLE
List out team in Description File

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#58]
@laxamanaj and @thomas-neitmann 

We should get someone to update the roster in the Description file 

![image](https://user-images.githubusercontent.com/10111024/218171779-baec5120-ecd1-4287-9c51-97718afd3c13.png)

**Comment by bms63** [comment]
I've gotten the pkgdown site to rebuild locally.  There is some weird stuff with `envsetup`, `pkglite` and `pilot1` packages that I am fussing around with.  Might need to call in some big guns.

**Comment by laxamanaj** [comment]
Adding here so we have the info, though list may need to be updated based on the who actually started any work with us : <html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Name | Email | Github userID | Company | Location | Time Zone
-- | -- | -- | -- | -- | --
Thomas Neitmann | thomas.neitmann@roche.com | thomas-neitmann | Roche | Basel, Switzerland | CET
Joel Laxmana | laxamana.joel@gene.com | laxamanaj | Roche | SSF, CA | PDT
Phanikumar Tata | phanikumar.tata@syneoshealth.com | pstata | Syneos Health | Austin,TX | CST
Robert Devine | rdevine@its.jnj.com | robertdevine | Johnson and Johnson | Spring House, PA | EST
Steven Haesendonckx | shaesen2@its.jnj.com | shaesen2 | Johnson and Johnson | Beerse, Belgium | CET
Rikimaru Nishimura | rnishim7@its.jnj.com | rnishim7 | Johnson and Johnson | Tokyo, Japan | JST
Yutong Liu | yutong.liu@modernatx.com | yutong1307 | Moderna | Durham, NC | EST
Lei Zhao | zhaol30@gene.com |   | Roche | SSF, CA | PDT
Nicole Jones | nicole.jones3@merck.com | nicolekjones | Merck | Rahway, NJ | EST
Benjamin Wang | benjamin.wang@merck.com | wangben718 | Merck | Rahway, NJ | EST
Ryan Johnson | ryan@posit.co | ryjohnson09 | Posit | Gaithersburg, MD | EST
Kangjie Zhang | kangjie.zhang@bayer.comkangjie0120@gmail.com | kaz462 | Bayer | Vancouver, Canada | PDT
Dadong Zhang | dzhang4@illumina.com | DadongZ | Illumina | Cary, NC | EST
Benjamin Straub | ben.x.straub@gsk.com |   |   |   |  
Declan Hodges | declan.x.hodges@gsk.com | DeclanHodges | GSK | Stevenage, UK | UTC


</body>
</html>

original google sheets roster : https://docs.google.com/spreadsheets/d/1BW9Jojo4bAgxbfM96nXooh2QAlU6CKwk19pInxmI2VA/edit?usp=sharing
