### ISSUE TITLE
Re-run TFLs with updated packages versions

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#6]
As we will use a much more recent CRAN snapshot than was used for the original pilot 1 some code might break due to changes/updates to the packages that were being used. Thus, we need to indentify if in fact any breaking changes were introduced and if so update the TFL programs accordingly.

**Comment by laxamanaj** [comment]
Since we forked the Pilot 1 repo, we should be able to get Pilot 1 programs from here : https://github.com/RConsortium/submissions-pilot3-adam/tree/main/vignettes 
I will create new issues for each TLG we need to generate per Pilot 1

**Comment by laxamanaj** [comment]
Let's close this as this is now being tracked seperately in #30 #29 #31 #32
