### ISSUE TITLE
Submission package set-up for pilot 3

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#61]
Hi, @zhaol30 .

Thanks for helping with this.  I just wanted to lay out the steps needed to help us check everything in P21 and prepare the eSUB package .

- [x] Get P21 access.  In Roche we currently have version 5.2.

- [x] Create a new data package in P21 called "Pilot 3 - Submissions WG"

- [x] The datasets can be downloaded from these areas : 
ADSL, ADAE, ADADAS - https://github.com/RConsortium/submissions-pilot3-adam/tree/main/submission/datasets
ADLBC -  https://github.com/RConsortium/submissions-pilot3-adam/blob/3_adlb/submission/datasets/adlbc.xpt
ADTTE - https://github.com/RConsortium/submissions-pilot3-adam/blob/adtte/submission/datasets/adtte.xpt
SDTM (DM, EX, AE) : https://github.com/RConsortium/submissions-pilot3-adam/tree/main/sdtm 

- [x] Please find the specs here : https://docs.google.com/spreadsheets/d/1gLm_IITesD8jUoygJ3rRQmLj1Wmt5P4NrteDogTWaI4/edit?usp=sharing when you download the specs, please remove the tab `Pilot3TeamUpdates` and remove any other datasets in the specs that are not listed above .  Then you should be able to import into P21 to re-export the `define.xml`

- [x] Once all, downloaded, they can be saved in a .zip to validate in P21

- [x] Upload P21 reports here, when ready and let Pilot 3 team know in slack.

Best
Joel
cc : @thomas-neitmann

**Comment by zhaol30** [comment]
[R-Consortium-R-tetsing-ADaM-validation-report-2023-02-22T21_39_06Z.xlsx](https://github.com/RConsortium/submissions-pilot3-adam/files/10808717/R-Consortium-R-tetsing-ADaM-validation-report-2023-02-22T21_39_06Z.xlsx)
Here's the P21 report for the 5 ADaM data sets and spec in the initial run. Please take a look at the "Issues" tab related to the data sets. No worries on the "GLOBAL" messages about missing define.xml or SDTM data sets. This will disappear after I run SDTM package.

**Comment by robertdevine** [comment]
Thank you, @zhaol30. Confirmed, we will confirm P21 validation prior to merge finalization (Issue #21). Really excellent! Thank you again.

**Comment by zhaol30** [comment]
Please find the P21 reports with update suggestion in this file. **Look into tab "Issue Details" Column K**. I'll rerun the package when these are fixed. Thanks everyone! 
[R-Consortium-R-tetsing-ADaM-validation-report_Feb 24 notes.xlsx](https://github.com/RConsortium/submissions-pilot3-adam/files/10827662/R-Consortium-R-tetsing-ADaM-validation-report_Feb.24.notes.xlsx)

**Comment by laxamanaj** [comment]
Hi, @zhaol30 .

Thanks again for the report on P21. I've listed them here for quicker review and check off.


- [ ] ADADAS			VARIABLE, LABEL	ANL01FL, Analysis Record Flag 01	[AD0018](https://roche-test.pinnacle21.net/data-packages/1065/reports/issues?issue=1975260)	Variable label mismatch between dataset and ADaM standard	Medium	Error	Variable Label should be : Analysis Flag 01

- [ ] ADADAS			VARIABLE, LABEL	ITTFL, Intent-to-Treat Population Flag	AD0018	Variable label mismatch between dataset and ADaM standard	Medium	Error	Variable Label should be: Intent to Treat Population Flag
- [ ] ADAE			VARIABLE, LABEL	AOCCFL, 1st Occurrence of Any AE Flag	[AD0018](https://roche-test.pinnacle21.net/data-packages/1065/reports/issues?issue=1975524)	Variable label mismatch between dataset and ADaM standard	Medium	Error	Variable Label should be: 1st Occurrence within Subject Flag
- [ ] ADAE			VARIABLE, LABEL	ADURU, AE Duration Units	AD0018	Variable label mismatch between dataset and ADaM standard	Medium	Error	Variable Label should be: Analysis Duration Units
- [ ] ADAE			VARIABLE, LABEL	ADURN, AE Duration (N)	AD0018	Variable label mismatch between dataset and ADaM standard	Medium	Error	Variable Label should be: Analysis Duration (N)
- [ ] ADAE		718	ADURU	DAY	[CT2002](https://roche-test.pinnacle21.net/data-packages/1065/reports/issues?issue=1975514)	ADURU value not found in 'Unit' extensible codelist	Medium	Warning	Please ensure the values are all in the codelist
- [ ] ADSL			DatasetLabel, Name	character(0), ADSL	[AD0320](https://roche-test.pinnacle21.net/data-packages/1065/reports/issues?issue=1976060)	Non-standard dataset label	Medium	Error	The dataset label for a dataset named 'ADSL' must be 'Subject-Level Analysis Dataset'.
- [ ] ADSL			VARIABLE	VISNUME	[AD1012](https://roche-test.pinnacle21.net/data-packages/1065/reports/issues?issue=1976128)	Secondary custom variable is present but its primary variable is not present	Medium	Warning	Check if VISNUME has the corresponding character variable, if not, we need to explain in ADRG
- [ ] ADTTE			VARIABLE, LABEL	STARTDT, Time to Event Origin Date for Subject	[AD0018](https://roche-test.pinnacle21.net/data-packages/1065/reports/issues?issue=1976472)	Variable label mismatch between dataset and ADaM standard	Medium	Error	Variable Label should be: Time-to-Event Origin Date for Subject
- [ ] ADTTE			VARIABLE, LABEL	SRCDOM, Source Domain	AD0018	Variable label mismatch between dataset and ADaM standard	Medium	Error	Variable Label should be: Source Data

**Comment by laxamanaj** [comment]
Hi, everyone.

I just went through all P21 issues as @zhaol30 went through in Friday's stand-up and for all issues above, I have updated all labels in our working define/specs and it is now in `main` per solutions in bold.  

**ACTION** : Since all adam scripts are now in `main` and capture variable labels using metacore/xportr from the specs **we all need to rerun our datasets in the `main` branch to get the matching labels before the next P21 run.  For anyone assigned to any of these datasets, please do a quick refresh/rerun of the datasets at your earliest convenience and let us know here when complete (I have already refreshed ADAE and have added the updates in the QC Findings Wiki).**

For the issue with the ADSL dataset label in the `adsl.R`, I went ahead and just quickly updated the program in `main` directly.  
```
xportr_write("submission/datasets/adsl.xpt",
               label = "Subject-Level Analysis Dataset"
  )
```
Just needs to be rerun and checked off, above, as well.

@zhaol30 , for the issue `ADSL.VISNUMEN`, please add this explanation to P21 so that we can resolve this issue. Add "_This is a Sponsor Extension to the ADaM Model. The VISNUMEN [End of Trt Visit (Vis 12 or Early Term.)] variable is a integer variable which is not related to any character variable._ ".  Once this is done, please check off above.

Hoping this resolves all of our P21 issues.  Thanks in advance all.

Best,
Joel

**Comment by laxamanaj** [comment]
Hi, @zhaol30 .

All .xpt datasets are now in the `main` branch.  The issues above should now be updated.  

XPT : https://github.com/RConsortium/submissions-pilot3-adam/tree/main/submission/datasets
define : https://github.com/RConsortium/submissions-pilot3-adam/blob/main/adam/TDF_ADaM%20-%20Pilot%203%20Team%20updated.xlsx (reminder : remove tab `Pilot3TeamUpdates` before reading into P21).

Can you please rerun P21 run to confirm issues are resolved?  Thanks in advance.

Best,
Joel

**Comment by robertdevine** [comment]
Thank you, @laxamanaj.

**Comment by laxamanaj** [comment]
### ACTION to Lei Zhao : Thanks to the discussion within the team, we should be able to resolve the issues directly in P21. Then Lei will :

##### 1)Update define directly in P21 to resolve issues with the specs. 
##### 2)Generate define.xml to validate against the ADaM .xpts
##### 3)re-export the updated Excel sheet so team can rerun their ADaM scripts against the new specs to make sure metatools and xportr functions are calling in the specs appropriately.

**Comment by laxamanaj** [comment]
The steps above have been completed.  Closing at this time.
