### ISSUE TITLE
update renv.lock to use admiral v0.10.0

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#77]
Hi, @DeclanHodges .  If you have bandwidth, I hope you can help with this.  
cc : @bms63

**Comment by thomas-neitmann** [comment]
I'd say we should not just update admiral but switch to a new CRAN snapshot and update all packages.

**Comment by DeclanHodges** [comment]
Hi all, I've started having a look into this. Please let me know if I'm heading in the wrong direction here as this is a first for me, but I had a look at the (CRAN snapshots)[https://cran.microsoft.com/snapshot/] and the latest snapshot I see says 2023-03-06, which is before `admiral` 0.10.0 was released on 2023-03-14. Is there a way to get a CRAN snapshot with the newest `admiral` release without it being listed in (CRAN snapshots)[https://cran.microsoft.com/snapshot/]?

**Comment by thomas-neitmann** [comment]
The CRAN snapshots from Microsoft have been deprecated. An alternative is RStudio Package Manager if I'm not mistaken @bms63 @robertdevine?

**Comment by DeclanHodges** [comment]
Thanks for the suggestion @thomas-neitmann! Posit Package Manager seems to work for providing us with a snapshot at the date we want. I've linked a PR where I'll put any further comments as I test running the programs with new package versions.
