### ISSUE TITLE
locf derivation in admiral v0.10.0 - check that datasets that use this derivation that all is working ok now.

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#78]
Hi, @kaz462 , I believe ADADAS is the only dataset that is using this.  Once @DeclanHodges PRs the new renv.lock file with updated admiral version to main, then you should be able to check this.

**Comment by kaz462** [comment]
Thanks, @laxamanaj @DeclanHodges ! I will work on this once https://github.com/RConsortium/submissions-pilot3-adam/pull/86 is merged

**Comment by laxamanaj** [comment]
Hi, @kaz462 .  Now that #86 is merged, are you able to update adadas using new locf function from admiral v0.10.0?  Thanks in advance!
