### ISSUE TITLE
review derivations specifications for ADSL

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#79]
review derivations specifications for ADSL

Hi, @DeclanHodges and @SHAESEN2 .  I know you mentioned that you've already done this check and that all derivations are written in the specs accordingly.  I just wanted formally 'check this off' so-to-speak.  Please close this to confirm ADSL specs are now complete.

This is the most up-to-date specs, where the define has 0 issues in Pinnacle 21 now.
https://docs.google.com/spreadsheets/d/13T15AS69ENeHktMofEQD4QBOg_moY-mU/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true

Please use your gmail account to open this link.

**Comment by DeclanHodges** [comment]
Hi both, I've done a final review and I'm happy to check this off. 

@SHAESEN2 - if you're okay with the specs too, then we can close this issue out.

**Comment by SHAESEN2** [comment]
All my previous comments are resolved. I'm OK with the specs.
