### ISSUE TITLE
Add SDTM data from CDISC pilot repo

### ISSUE THREAD

**Issue by thomas-neitmann** [RConsortium/submissions-pilot3-adam#8]
Currently this repo only contains the ADaM datasets from the CDISC pilot. Let's create a folder `sdtm` that contains **all** SDTM datasets found [here](https://github.com/phuse-org/phuse-scripts/tree/master/data/sdtm/cdiscpilot01).

**Comment by robertdevine** [comment]
For purposes of provenance and traceability, the _submissions-pilot3-adam_ repository sdtm folder will capture the commit history from the SDTM datasets located in the CDISC pilot repo at the link above.

**Comment by SHAESEN2** [comment]
Why not from the original repo from CDISC?

**Comment by thomas-neitmann** [comment]
Which one would that be @SHAESEN2? I pasted the link from the pilot 1 README here...

**Comment by SHAESEN2** [comment]
> Which one would that be @SHAESEN2? I pasted the link from the pilot 1 README here...

I believe it is this one, but I am not sure if the datasets have been updated while moving to github
https://github.com/cdisc-org/sdtm-adam-pilot-project
