### ISSUE TITLE
review derivations specifications for ADADAS

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#81]
I know you mentioned that you've already done this check and that all derivations are written in the specs accordingly. I just wanted formally 'check this off' so-to-speak. Please close this to confirm ADADAS specs are now complete.

This is the most up-to-date specs, where the define has 0 issues in Pinnacle 21 now.
https://docs.google.com/spreadsheets/d/13T15AS69ENeHktMofEQD4QBOg_moY-mU/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true

Please use your gmail account to open this link.

**Comment by kaz462** [comment]
Thanks @laxamanaj for putting everything together! Yes, ADADAS spec is complete.

**Comment by laxamanaj** [comment]
Thank you, @kaz462 !
