### ISSUE TITLE
review derivations specifications for ADLBC

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#82]
Please check this to confirm ADLBC specs are now complete.

This is the most up-to-date specs, where the define has 0 issues in Pinnacle 21 now.
https://docs.google.com/spreadsheets/d/13T15AS69ENeHktMofEQD4QBOg_moY-mU/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true

Please use your gmail account to open this link. Direct message me in slack your gmail so that I can share the doc.

**Comment by DadongZ** [comment]
@laxamanaj @nicolekjones One kind of weird thing that I observed is that the metacore object created from the excel file for ADLBC, `adlbc_spec`, seems no `ADLBC.AVAL` in the `adlbc_spec$derivations`:

```
metacore <- spec_to_metacore("adam/TDF_ADaM - Pilot 3 Team updated.xlsx", where_sep_sheet = FALSE)

adlbc_spec <- metacore %>%
  select_dataset("ADLBC")
adlbc_spec$derivations
    derivation_id
1      ADLBC.A1HI
2      ADLBC.A1LO
3     ADLBC.ABLFL
4       ADLBC.ADT
5       ADLBC.ADY
6  ADLBC.AENTMTFL
7       ADLBC.AGE
8    ADLBC.AGEGR1
9   ADLBC.AGEGR1N
10 ADLBC.ALBTRVAL
11  ADLBC.ANL01FL
12   ADLBC.ANRIND
13   ADLBC.AVISIT
14  ADLBC.AVISITN
15     ADLBC.BASE
16   ADLBC.BNRIND
17  ADLBC.BR2A1HI
18  ADLBC.BR2A1LO
19      ADLBC.CHG
20 ADLBC.COMP24FL
21  ADLBC.DSRAEFL
22  ADLBC.LBNRIND
23    ADLBC.LBSEQ
24 ADLBC.LBSTRESN
25    ADLBC.PARAM
26  ADLBC.PARAMCD
27   ADLBC.PARAMN
28  ADLBC.PARCAT1
29   ADLBC.R2A1HI
30   ADLBC.R2A1LO
31     ADLBC.RACE
32    ADLBC.RACEN
33    ADLBC.SAFFL
34      ADLBC.SEX
35  ADLBC.STUDYID
36   ADLBC.SUBJID
37     ADLBC.TRTA
38    ADLBC.TRTAN
39   ADLBC.TRTEDT
40     ADLBC.TRTP
41    ADLBC.TRTPN
42   ADLBC.TRTSDT
43  ADLBC.USUBJID
44    ADLBC.VISIT
45 ADLBC.VISITNUM
```
There are supposed to be 46 rows but 45 was imported with ADLBC.AVAL being missed.

**Comment by DadongZ** [comment]
@robertdevine there is one warning when calculating the `maxALBTRVAL = max(ALBTRVAL, na.rm = TRUE)` `group_by` `USUBJID` and `PARAMCD`. The warning came from the `USUBJID=01-704-1323` because all ALBTRVAL values are NAs and it returned with `-Inf` for maxALBTRVAL. This warning does't affect the accuracy of the derived variable ANL01FL. 
```
# Derive ANL01FL
adlb09 <- adlb08 %>%
      filter((VISITNUM >= 4 & VISITNUM <= 12) & !grepl("UN", VISIT)) %>%
      group_by(USUBJID, PARAMCD) %>%
      mutate(
        maxALBTRVAL = max(ALBTRVAL, na.rm = T),
        ANL01FL = ifelse(maxALBTRVAL == ALBTRVAL, "Y", "")
      ) %>%
      arrange(desc(ANL01FL))
Warning message:
Problem while computing `maxALBTRVAL = max(ALBTRVAL, na.rm = T)`.
ℹ no non-missing arguments to max; returning -Inf
ℹ The warning occurred in group 1373: USUBJID = "01-704-1323", PARAMCD = "BILI". 

table(adlb09$ANL01FL, exclude = NULL)

    Y  <NA> 
 5490 31642 
```

If prefer we can fix it by `maxALBTRVAL = ifelse(all(is.na(ALBTRVAL)), NA, max(ALBTRVAL, na.rm = T))`:
```
# Derive ANL01FL
adlb09 <- adlb08 %>%
      filter((VISITNUM >= 4 & VISITNUM <= 12) & !grepl("UN", VISIT)) %>%
      group_by(USUBJID, PARAMCD) %>%
      mutate(
        maxALBTRVAL = ifelse(all(is.na(ALBTRVAL)), NA, max(ALBTRVAL, na.rm = T)),
        ANL01FL = ifelse(maxALBTRVAL == ALBTRVAL, "Y", "")
      ) %>%
      arrange(desc(ANL01FL)) %>% 
      select(USUBJID, PARAMCD, LBSEQ, ANL01FL) %>%
      slice(1) %>%
      full_join(adlb08, by = c("USUBJID", "PARAMCD", "LBSEQ"))

table(adlb09$ANL01FL, exclude = NULL)

    Y  <NA> 
 5490 31642 
```

**Comment by DadongZ** [comment]
> Thank you @DadongZ. Maybe we can discuss further at tomorrow's Check In.
> 
> In my Posit Cloud sandbox, I cannot replicate the (45 of 46) result. Rather, in my test runs 46 (of 46) rows are returned (including AVAL) and the specs appear to be correct.

@robertdevine thank you for the info. I'd think It is likely due to the R version. I forked the repository and ran it locally under R v4.2.2. It's great that you didn't see the issue in Posit Cloud.

**Comment by robertdevine** [comment]
Thank you, @DadongZ.

**Comment by nicolekjones** [comment]
Thank you @DadongZ and @robertdevine for looking into this

The reason that AVAL is missing is because the spec file doesn't contain a derivation for AVAL so metacore is processing this correctly. The spec file needs to be updated to solve this problem. I am currently working to resolve this and verify that all the correct derivations are present. Should have an update by the end of today.
