### ISSUE TITLE
review derivations specifications for ADTTE

### ISSUE THREAD

**Issue by laxamanaj** [RConsortium/submissions-pilot3-adam#83]
Please check this to confirm ADTTE specs are now complete.

This is the most up-to-date specs, where the define has 0 issues in Pinnacle 21 now.
https://docs.google.com/spreadsheets/d/13T15AS69ENeHktMofEQD4QBOg_moY-mU/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true

Please use your gmail account to open this link. Direct Message me in slack your gmail so that I can share the document with you.

**Comment by robertdevine** [comment]
Thanks @laxamanaj. Sent you a Direct Message in slack with my gmail info.  Thx. again.

**Comment by robertdevine** [comment]
Thanks @SHAESEN2. Confirmed in Posit Cloud sandbox.

A simple select of  the ADTTE dataset using 'spec_to_metacore'
to pull the ADTTE variables (from the March 22, 2023 update 
by@laxamanaj)  then review of 'derivation_id' and 'derivation' 
shows 26 of 26 ADTTE variables with the specs correct.

@wangben718 can you please re-confirm as well for issue closure.

Thank you everyone.

**Comment by wangben718** [comment]
Looks good to me.

**Comment by robertdevine** [comment]
Thank you, @wangben718.

**Comment by laxamanaj** [comment]
Thanks all for your review.
