### ISSUE TITLE
document label discrepancies 

### ISSUE THREAD

**Issue by kaz462** [RConsortium/submissions-pilot3-adam#85]
some variable labels are updated to pass the P21E checks per ADaM IG 1.1, document the changes in [wiki: Label discrepancies](https://github.com/RConsortium/submissions-pilot3-adam/wiki/QC-Findings#label-discrepancies)

@laxamanaj the current spec used in main has label for `ADSL.ITTFL` as "Intent to Treat Population Flag", but the label from most recent spec is "Intent-To-Treat Population Flag", which caused some attributes discrepancies. should we use the spec from below link instead?

https://docs.google.com/spreadsheets/d/13T15AS69ENeHktMofEQD4QBOg_moY-mU/edit?usp=sharing&ouid=103991081896680964420&rtpof=true&sd=true

**Comment by kaz462** [comment]
@laxamanaj seems https://github.com/RConsortium/submissions-pilot3-adam/pull/84 has the most recent spec? I will check this PR instead for label discrepancies

**Comment by laxamanaj** [comment]
Thanks for helping with this, @kaz462 .  Yes, #84 has the latest spec.  In branch #10 _update_define, the latest spec will be in the adam directory.

**Comment by kaz462** [comment]
thanks @laxamanaj !
